name: Scheduled Release

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check-and-release:
    name: Check for changesets and release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Check for changeset files
        id: check-changesets
        run: |
          # Count markdown files in .changeset folder excluding README.md
          changeset_count=$(find .changeset -name "*.md" -not -name "README.md" | wc -l)
          echo "Found $changeset_count changeset files"
          echo "has_changesets=$([[ $changeset_count -gt 0 ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Setup Node.js 20.x
        if: steps.check-changesets.outputs.has_changesets == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        if: steps.check-changesets.outputs.has_changesets == 'true'
        run: |
          npm i

      - name: Create Release Pull Request or Publish to npm
        if: steps.check-changesets.outputs.has_changesets == 'true'
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run ci:version
          publish: npm run ci:release
          ignore: microfox-scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
